name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:

  build:
    name: test-go${{ matrix.goversion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goversion: ['1.17']

    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.goversion }}
      id: go

    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Run tests
      run: |
        make test
